id: Radio_Nowy_Swiat_OFF
alias: Radio_Nowy_Swiat_OFF
initial_state: 'on'
trigger:
- platform: state
  entity_id: input_boolean.radio_nowy_swiat
  to: 'off'
condition: []
action:
- service: media_player.turn_off
  data:
    entity_id: media_player.salon2