- platform: burze_dzis_net
  api_key: !secret burze_key
  warnings:
    - frost_warning
    - heat_warning
    - wind_warning
    - precipitation_warning
    - storm_warning
    - tornado_warning
  latitude: !secret burze_lat
  longitude: !secret burze_long
  storms_nearby:
    radius: 30
    