esphome:
  name: sonoff_gabinet_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SfGtLt"
    password: !secret ap_password

logger:

api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_state:
      then:
        - light.toggle: light_1

  - platform: status
    name: "Gabinet Swiatlo Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "Gabinet Swiatlo"
    id: light_1
    output: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: yes