esphome:
  name: sonoff_tv_pow
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SfPowTv"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    current:
      name: "TV Current"
    voltage:
      name: "TV Voltage"
    power:
      name: "TV Power"
      id: my_power
    update_interval: 60s
  - platform: total_daily_energy
    name: "TV Total Daily Energy"
    power_id: my_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "TV Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "TV Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO15
    inverted: yes

time:
  - platform: sntp
    id: my_time

